runtime: php74

runtime_config:
  document_root: .

entrypoint:
  serve index.php

handlers:
  # Serve images as static resources.
  - url: /(.+\.(gif|png|jpg))$
    static_files: \1
    upload: .+\.(gif|png|jpg)$

  # Serve php scripts.
  - url: /(.+\.php)$
    script: \1

env_variables:
  CLOUDSQL_USER: root
  CLOUDSQL_DB: saitynai
  CLOUDSQL_PASSWORD:
  CLOUDSQL_DSN: /cloudsql/saitynai-370408:us-central1:saitynai1