#customer_list:
#  path: /api/v1/customers
#  controller: App\Controller\CustomerController:indexAction
#  methods: [GET]
#
#customer_show:
#  path: /api/v1/customers/show/{id}
#  controller: App\Controller\CustomerController:show
#  methods: [GET]
#
#customer_create:
#  path: /api/v1/customers
#  controller: App\Controller\CustomerController:createAction
#  methods: [POST]
#
#customer_edit:
#  path: /api/v1/customers/edit/{id}
#  controller: App\Controller\CustomerController:edit
#  methods: [POST]
#
#location_list:
#  path: /api/v1/locations
#  controller: App\Controller\LocationController::indexAction
#  methods: [GET]
#
#location_create:
#  path: /api/v1/locations
#  controller: App\Controller\LocationController::createAction
#  methods: [POST]
#
#machine_list:
#  path: /api/v1/machines
#  controller: App\Controller\MachineController::indexAction
#  methods: [GET]
#
#machine_create:
#  path: /api/v1/machines
#  controller: App\Controller\MachineController::createAction
#  methods: [POST]
